image: omos/argon2-gpu:zesty

before_script:
    - git submodule update --init

cache:
    paths:
        - "build-cuda/"
        - "build-nocuda/"

cuda:
    script:
        - mkdir -p build-cuda
        - cd build
        - cmake ..
        - make
        #- CTEST_OUTPUT_ON_FAILURE=1 make test

nocuda:
    script:
        - mkdir -p build-nocuda
        - cd build
        - cmake -DNO_CUDA=TRUE ..
        - make
        #- CTEST_OUTPUT_ON_FAILURE=1 make test
