image: omos/argon2-gpu:zesty

before_script:
    - git submodule update --init

cache:
    paths:
        - "build/"

gcc-cuda:
    stage: Build
    script:
        - export COMPILER=gcc
        - export CUDA=cuda
        - . scripts/ci.sh

gcc-nocuda:
    stage: Build
    script:
        - export COMPILER=gcc
        - export CUDA=nocuda
        - . scripts/ci.sh

clang-cuda:
    stage: Build
    script:
        - export COMPILER=clang
        - export CUDA=cuda
        - . scripts/ci.sh

clang-nocuda:
    stage: Build
    script:
        - export COMPILER=clang
        - export CUDA=nocuda
        - . scripts/ci.sh
